language: node_js
node_js:
  - "12"

branches:
  only:
    - ejemploenvivo
 
git:
  submodules: false
  depth: false
  


script: 
  - ./travis-script.sh
  - echo "Ejecucion de script .sh!"

deploy:
  provider: pages
  skip-cleanup: true
  target-branch: master # Commit to master instead of gh-pages
  github-token: $GH_TOKEN
  keep-history: true # By default, Travis uses push --force and wipes out commit history
  verbose: true
  on:
    branch: ejemploenvivo