language: node_js
node_js:
  - "12"

branches:
  except:
    - testing
 
git:
  submodules: false
  depth: false
  
install:
  - npm ci

script: 
  - ./travisScript.sh
  - echo "Ejecucion de script .sh!"

after_success:
  - git checkout master
  - git merge pruebas --no-ff -m "Merge desde travis a MASTER :)"
  - git push origin master