language: node_js
node_js:
  - "12"

git:
  submodules: false
  depth: false
install:
  - npm ci

script: 
  - ./travisScript.sh
  - echo "Ejecucion de script .sh!"

branches:
  except:
    - testing
