codecov:
  token: "08f1a0cd-798f-439b-9a64-5eaa34759419"
  bot: "codecov-io"
  ci:
    - "github.com"
  strict_yaml_branch: "yaml-config"
  max_report_age: 24
  disable_default_path_fixes: no
  require_ci_to_pass: yes
  notify:
    after_n_builds: 2
    wait_for_ci: yes
